In [1]:
import pandas as pd, numpy as np

In [2]:
df = pd.read_csv("../../data/processed/기아_차종별판매실적_전처리.csv")

In [3]:
df

,차종,차량 구분,거래 유형,1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월,연도
0,Morning,일반 차량,국내,1813.0,2049.0,2127.0,2164.0,2502.0,2245.0,2033.0,2910.0,1892.0,2225.0,2111.0,1808.0,2023
1,Ray,일반 차량,국내,3585.0,4268.0,4155.0,4158.0,4576.0,4372.0,4285.0,4402.0,3464.0,4824.0,4587.0,4254.0,2023
2,K3,일반 차량,국내,950.0,1024.0,1197.0,670.0,975.0,1540.0,976.0,1123.0,1036.0,939.0,1428.0,1346.0,2023
3,K5,일반 차량,국내,2560.0,2653.0,3421.0,2739.0,3166.0,2963.0,2246.0,2613.0,2280.0,2592.0,3783.0,3563.0,2023
4,Stinger,일반 차량,국내,113.0,120.0,143.0,61.0,45.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,PV5,일반 차량,수출,0,0,0,0,0,0,0,0,0,0,0,0,2025
143,Tasman,특수 차량,수출,0,0,0,0,0,0,0,0,0,0,0,0,2025
144,Military,특수 차량,수출,0,0,0,0,0,0,0,0,0,0,0,0,2025
145,Bongo,특수 차량,수출,17,0,0,0,0,0,0,0,0,0,0,0,2025
146,Bus,특수 차량,수출,0,0,0,0,0,0,0,0,0,0,0,0,2025

In [4]:
df["차종"] = df["차종"].str.strip()

In [5]:
df

,차종,차량 구분,거래 유형,1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월,연도
0,Morning,일반 차량,국내,1813.0,2049.0,2127.0,2164.0,2502.0,2245.0,2033.0,2910.0,1892.0,2225.0,2111.0,1808.0,2023
1,Ray,일반 차량,국내,3585.0,4268.0,4155.0,4158.0,4576.0,4372.0,4285.0,4402.0,3464.0,4824.0,4587.0,4254.0,2023
2,K3,일반 차량,국내,950.0,1024.0,1197.0,670.0,975.0,1540.0,976.0,1123.0,1036.0,939.0,1428.0,1346.0,2023
3,K5,일반 차량,국내,2560.0,2653.0,3421.0,2739.0,3166.0,2963.0,2246.0,2613.0,2280.0,2592.0,3783.0,3563.0,2023
4,Stinger,일반 차량,국내,113.0,120.0,143.0,61.0,45.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,PV5,일반 차량,수출,0,0,0,0,0,0,0,0,0,0,0,0,2025
143,Tasman,특수 차량,수출,0,0,0,0,0,0,0,0,0,0,0,0,2025
144,Military,특수 차량,수출,0,0,0,0,0,0,0,0,0,0,0,0,2025
145,Bongo,특수 차량,수출,17,0,0,0,0,0,0,0,0,0,0,0,2025
146,Bus,특수 차량,수출,0,0,0,0,0,0,0,0,0,0,0,0,2025

In [7]:
df.to_csv("../../data/processed/기아_차종별판매실적_전처리.csv", index=False)